# Generated by Django 2.1.7 on 2019-03-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.CharField(max_length=10, verbose_name='Ano')),
                ('cor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('age', models.IntegerField(default=0, verbose_name='Idade')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('email', models.EmailField(max_length=50)),
                ('data_nascimento', models.DateTimeField(verbose_name='Data Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('ud', models.CharField(max_length=2)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular_1', models.CharField(max_length=20)),
                ('celular_2', models.CharField(max_length=20)),
                ('fixo', models.CharField(max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.AddField(
            model_name='automovel',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
    ]
