# Generated by Django 2.1.7 on 2019-03-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automovel',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='client_id',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
    ]
