# Generated by Django 2.1.7 on 2019-03-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190314_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='ud',
            new_name='uf',
        ),
    ]
