# Generated by Django 2.1.7 on 2019-03-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190314_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data Nascimento'),
        ),
    ]
